// src/components/EditHabitModal.tsx
import React, { useState, useEffect } from "react";
import { Habit, updateHabit, syncHabitLogsSharedWith } from "../lib/api";
import { UserProfile } from "../pages/Social";
import { supabase } from "../lib/supabase";
import { X, Trash2 } from "lucide-react";

interface Friendship {
  participants: string[];
  status: string;
}

export const EditHabitModal = ({
  habit,
  userId,
  onClose,
  onSave,
  onDelete
}: {
  habit: Habit;
  userId: string;
  onClose: () => void;
  onSave: () => void;
  onDelete: () => void;
}) => {
  const [title, setTitle] = useState(habit.title);
  const [description, setDescription] = useState(habit.description || "");
  const [color, setColor] = useState(habit.color);
  const [sharedWith, setSharedWith] = useState<string[]>(habit.sharedWith || []);
  
  const [friends, setFriends] = useState<{ id: string; email: string; displayName: string }[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const loadFriends = async () => {
      const { data: acc, error } = await supabase.from('friendships')
        .select('*')
        .contains('participants', [userId])
        .eq('status', 'accepted');
        
      if (error || !acc) return;
      
      const friendIds = new Set<string>();
      acc.forEach(f => {
        friendIds.add(f.participants[0]);
        friendIds.add(f.participants[1]);
      });
      friendIds.delete(userId);

      if (friendIds.size === 0) {
        setFriends([]);
        return;
      }

      const { data: usersData } = await supabase.from('users')
        .select('*')
        .in('id', Array.from(friendIds));

      if (usersData) {
        setFriends(usersData as any[]);
      }
    };
    loadFriends();
  }, [userId]);

  const toggleShare = (fid: string) => {
    if (sharedWith.includes(fid)) {
      setSharedWith(sharedWith.filter(id => id !== fid));
    } else {
      setSharedWith([...sharedWith, fid]);
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const updated = { ...habit, title, description, color, sharedWith };
    await updateHabit(habit.id, { title, description, color, sharedWith });
    await syncHabitLogsSharedWith(updated);
    setLoading(false);
    onSave();
  };

  const colors = ["#3b82f6", "#ef4444", "#10b981", "#f59e0b", "#6366f1", "#ec4899"];

  return (
    <div className="fixed inset-0 bg-slate-900/60 dark:bg-black/70 z-[100] flex items-center justify-center p-4">
      <div className="bg-white dark:bg-gray-900 rounded-2xl w-full max-w-md shadow-xl border border-gray-100 dark:border-gray-800 overflow-hidden flex flex-col max-h-[90vh]">
        <div className="flex items-center justify-between p-4 border-b border-slate-100 dark:border-gray-800">
          <h2 className="text-lg font-bold text-slate-800 dark:text-gray-100">Edit Habit</h2>
          <button onClick={onClose} className="p-2 hover:bg-slate-100 dark:hover:bg-gray-800 rounded-full transition-colors">
            <X className="w-5 h-5 text-slate-500 dark:text-gray-400" />
          </button>
        </div>
        
        <form onSubmit={handleSave} className="p-4 md:p-6 overflow-y-auto space-y-6">
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-1">Title</label>
              <input
                type="text"
                required
                value={title}
                onChange={e => setTitle(e.target.value)}
                className="w-full px-3 py-2 bg-slate-50 dark:bg-gray-800 border border-slate-200 dark:border-gray-700 rounded-lg text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 placeholder:text-gray-400 dark:placeholder:text-gray-600"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-1">Color</label>
              <div className="flex gap-2 flex-wrap">
                {colors.map(c => (
                  <button
                    key={c}
                    type="button"
                    onClick={() => setColor(c)}
                    className="w-8 h-8 rounded-full flex items-center justify-center transition-transform hover:scale-110"
                    style={{ backgroundColor: c, border: color === c ? '2px solid #1e293b' : 'none' }}
                  >
                    {color === c && <div className="w-3 h-3 bg-white rounded-full" />}
                  </button>
                ))}
              </div>
            </div>

            <div className="pt-2 border-t border-slate-100 dark:border-gray-800">
              <label className="block text-sm font-medium text-slate-700 dark:text-gray-300 mb-2">Share with friends</label>
              {friends.length === 0 ? (
                <div className="text-sm text-slate-500 dark:text-gray-400 bg-slate-50 dark:bg-gray-800 p-3 rounded-lg border border-slate-100 dark:border-gray-700">
                  You haven't added any friends yet. Add friends on the Social tab.
                </div>
              ) : (
                <div className="space-y-2 max-h-48 overflow-y-auto pr-2 border p-2 rounded-lg border-slate-100 dark:border-gray-700 bg-slate-50/50 dark:bg-gray-800/50">
                  {friends.map(f => (
                    <label key={f.id} className="flex items-center gap-3 p-2 hover:bg-slate-100 dark:hover:bg-gray-700 rounded-md cursor-pointer transition-colors border border-transparent">
                      <input
                        type="checkbox"
                        checked={sharedWith.includes(f.id)}
                        onChange={() => toggleShare(f.id)}
                        className="w-4 h-4 rounded text-blue-600 focus:ring-blue-500 border-slate-300 dark:border-gray-600"
                      />
                      <span className="text-sm font-medium text-slate-800 dark:text-gray-200">{f.displayName}</span>
                    </label>
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-gray-800">
            <button
              type="button"
              onClick={onDelete}
              className="flex items-center gap-2 px-4 py-2 text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/30 rounded-lg text-sm font-medium transition-colors"
            >
              <Trash2 className="w-4 h-4" />
              Delete
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex items-center gap-2 px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
            >
              {loading ? "Saving..." : "Save Changes"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// app/components/EditHabitModal.vue
<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div 
      v-motion 
      :initial="{ opacity: 0 }" 
      :enter="{ opacity: 1 }" 
      class="fixed inset-0 bg-slate-900/40 backdrop-blur-sm transition-opacity" 
      @click="close"
    ></div>

    <div 
      v-motion 
      :initial="{ opacity: 0, y: 20, scale: 0.95 }" 
      :enter="{ opacity: 1, y: 0, scale: 1, transition: { type: 'spring', stiffness: 300, damping: 25 } }"
      class="relative bg-white dark:bg-slate-900 rounded-2xl shadow-xl w-full max-w-md overflow-hidden border border-slate-200 dark:border-slate-800"
    >
      <div class="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
        <h3 class="text-lg font-semibold text-slate-900 dark:text-white" id="modal-title">
          {{ habit.id ? 'Edit Habit' : 'New Habit' }}
        </h3>
        <button @click="close" class="text-slate-400 hover:text-slate-500 dark:hover:text-slate-300 transition-colors">
          <X class="w-5 h-5" />
        </button>
      </div>

      <div class="p-6 space-y-5">
        <div>
          <label class="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Title</label>
          <input 
            v-model="editHabit.title" 
            type="text" 
            autoFocus
            class="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-colors text-slate-900 dark:text-white sm:text-sm outline-none"
          >
        </div>

        <div>
          <label class="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">Color</label>
          <div class="flex flex-wrap gap-2">
            <button
              v-for="color in presetColors"
              :key="color"
              type="button"
              @click="editHabit.color = color"
              class="w-8 h-8 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-slate-900 transition-transform hover:scale-110 cursor-pointer"
              :class="editHabit.color === color ? 'ring-2 ring-offset-2 ring-indigo-500 dark:ring-offset-slate-900 scale-110' : ''"
              :style="{ backgroundColor: color }"
            />
          </div>
        </div>
      </div>

      <div class="px-6 py-4 bg-slate-50 dark:bg-slate-900/50 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
        <button 
          v-if="habit.id"
          @click="onDelete"
          class="text-sm font-medium text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 transition-colors flex items-center gap-1 cursor-pointer"
        >
          <Trash2 class="w-4 h-4" />
          Delete
        </button>
        <div v-else></div>

        <div class="flex items-center gap-3">
          <button @click="close" class="px-4 py-2 text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors cursor-pointer">
            Cancel
          </button>
          <button @click="save" class="px-4 py-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg transition-colors shadow-sm cursor-pointer">
            Save Changes
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { X, Trash2 } from 'lucide-vue-next';
import type { Habit } from '~/composables/useHabitsApi';

const props = defineProps<{
  isOpen: boolean
  habit: Partial<Habit>
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'save', habit: Partial<Habit>): void
  (e: 'delete', id: string): void
}>()

const presetColors = [
  '#f87171', '#fb923c', '#fbbf24', '#a3e635', 
  '#34d399', '#2dd4bf', '#38bdf8', '#818cf8', 
  '#a78bfa', '#e879f9', '#f43f5e'
];

const editHabit = ref<Partial<Habit>>({ ...props.habit })

watch(() => props.habit, (newHabit) => {
  editHabit.value = { ...newHabit }
}, { deep: true })

const close = () => {
  emit('close');
}

const save = () => {
  emit('save', editHabit.value);
}

const onDelete = () => {
  if (confirm("Are you sure you want to delete this habit?") && editHabit.value.id) {
    emit('delete', editHabit.value.id);
  }
}
</script>
